using AccessiblePdfEditor.Model.Forms;
using PdfSharp.Pdf;
using PdfSharp.Pdf.Advanced;

namespace AccessiblePdfEditor.Persistence;

// =====================================================================================
//  FormWriter.cs
//
//  Writes filled form values back into a PDF.
//
//  Everything here works on RAW dictionaries rather than PDFsharp's typed AcroForm classes,
//  and that is a deliberate decision taken on evidence rather than preference. Testing
//  against PDFsharp 6.2.4 found three separate defects in the typed API:
//
//    PdfRadioButtonField.SelectedIndex  writes "/V /21 0 R" — a name containing an object
//                                       reference — producing a document in which nothing
//                                       is selected and the value is unreadable.
//    PdfComboBoxField.SelectedIndex     writes "/V (\(Netherlands\))" — the parentheses end
//    PdfListBoxField.SelectedIndex      up inside the string, so the value matches no option.
//
//  All three produce files that save without error and are silently wrong. For a blind
//  user filling in a form they cannot see, "saved successfully but the answers are corrupt"
//  is the worst possible failure: nothing in the process tells them anything went wrong.
//
//  A further reason: merely READING doc.AcroForm.Fields[0] throws unless a font resolver
//  has been installed, because the typed field constructor builds an XFont. The raw path
//  has no font dependency at all, so form filling works even on a machine where font
//  handling is unavailable.
//
//  So: raw dictionaries for every field type, appearances generated by hand, and
//  /NeedAppearances set as well for viewers that honour it.
// =====================================================================================

#region FieldWriteResult

/// <summary>The outcome of writing one field's value.</summary>
public readonly record struct FieldWriteResult(bool Written, string? Warning)
{
    public static FieldWriteResult Ok() => new(true, null);

    public static FieldWriteResult OkWithWarning(string warning) => new(true, warning);

    public static FieldWriteResult NotWritten(string reason) => new(false, reason);
}

#endregion

#region RawField — a field and the widgets that draw it

/// <summary>
/// One form field as it exists in the file: its own dictionary, and the widget annotations that
/// display it. A field usually has exactly one widget merged into the same dictionary, but a radio
/// group has one per button and a field repeated across pages has one per appearance.
/// </summary>
internal sealed class RawField
{
    public RawField(string fullName, PdfDictionary dictionary, IReadOnlyList<PdfDictionary> widgets)
    {
        FullName = fullName;
        Dictionary = dictionary;
        Widgets = widgets;
    }

    /// <summary>The field's fully qualified dotted name.</summary>
    public string FullName { get; }

    /// <summary>The field dictionary, which holds /V and /Ff.</summary>
    public PdfDictionary Dictionary { get; }

    /// <summary>The widget annotations that draw this field.</summary>
    public IReadOnlyList<PdfDictionary> Widgets { get; }

    /// <summary>
    /// The single widget for a field, when it has exactly one. Most fields do, and the ones that
    /// do not are handled explicitly by the code that needs them.
    /// </summary>
    public PdfDictionary? SingleWidget => Widgets.Count == 1 ? Widgets[0] : null;
}

#endregion

#region RawFormAccess — reaching the AcroForm without the typed API

/// <summary>
/// Provides access to a document's form fields as raw dictionaries, bypassing PDFsharp's typed
/// AcroForm classes entirely.
/// </summary>
internal sealed class RawFormAccess
{
    #region Construction

    private RawFormAccess(PdfDocument document, PdfDictionary acroForm, Dictionary<string, RawField> fields)
    {
        Document = document;
        AcroForm = acroForm;
        Fields = fields;
    }

    public PdfDocument Document { get; }

    public PdfDictionary AcroForm { get; }

    /// <summary>Every terminal field, keyed by fully qualified name.</summary>
    public IReadOnlyDictionary<string, RawField> Fields { get; }

    /// <summary>
    /// Opens a document's form. Returns null when it has none, which is not an error — most PDFs
    /// are not forms.
    /// </summary>
    public static RawFormAccess? Open(PdfDocument document)
    {
        try
        {
            var acroForm = document.Internals.Catalog.Elements.GetDictionary("/AcroForm");
            if (acroForm is null)
                return null;

            var roots = acroForm.Elements.GetArray("/Fields");
            if (roots is null || roots.Elements.Count == 0)
                return null;

            var fields = new Dictionary<string, RawField>(StringComparer.Ordinal);

            for (int i = 0; i < roots.Elements.Count; i++)
            {
                var field = ResolveDictionary(roots.Elements[i]);
                if (field is not null)
                    Collect(field, prefix: null, fields);
            }

            return new RawFormAccess(document, acroForm, fields);
        }
        catch
        {
            return null;
        }
    }

    /// <summary>
    /// Walks the field tree, building fully qualified names and gathering each terminal field's
    /// widgets.
    ///
    /// The distinction that matters: a node with /Kids whose children have their OWN /T is an
    /// intermediate node and the walk continues; a node whose kids have no /T is a terminal field
    /// whose kids are its widget annotations. Getting this backwards would treat every radio button
    /// as a separate field and make the group unselectable.
    /// </summary>
    private static void Collect(PdfDictionary field, string? prefix, Dictionary<string, RawField> into)
    {
        string partial = field.Elements.GetString("/T") ?? string.Empty;

        string fullName = string.IsNullOrEmpty(prefix)
            ? partial
            : string.IsNullOrEmpty(partial) ? prefix : $"{prefix}.{partial}";

        var kids = field.Elements.GetArray("/Kids");

        if (kids is null || kids.Elements.Count == 0)
        {
            // No kids: the field and its widget are merged into one dictionary.
            if (fullName.Length > 0)
                into[fullName] = new RawField(fullName, field, [field]);

            return;
        }

        var children = new List<PdfDictionary>(kids.Elements.Count);

        for (int i = 0; i < kids.Elements.Count; i++)
        {
            var kid = ResolveDictionary(kids.Elements[i]);
            if (kid is not null)
                children.Add(kid);
        }

        bool kidsAreFields = children.Any(k => k.Elements.ContainsKey("/T"));

        if (kidsAreFields)
        {
            foreach (var child in children)
                Collect(child, fullName, into);

            return;
        }

        // Kids without names are widget annotations belonging to this field.
        if (fullName.Length > 0)
            into[fullName] = new RawField(fullName, field, children);
    }

    /// <summary>
    /// Resolves an array entry to a dictionary, following an indirect reference when there is one.
    /// Field trees are almost entirely built from references, so this is the normal case.
    /// </summary>
    private static PdfDictionary? ResolveDictionary(PdfItem? item) => item switch
    {
        PdfReference reference => reference.Value as PdfDictionary,
        PdfDictionary dictionary => dictionary,
        _ => null,
    };

    #endregion

    #region Form-level settings

    /// <summary>
    /// Asks viewers to regenerate field appearances.
    ///
    /// Set as a fallback, never as the plan: Acrobat honours it, but the built-in viewers in Chrome
    /// and Edge ignore it completely. The appearances this editor generates are what actually make
    /// a filled form visible; this flag is what covers the cases where a generated appearance is
    /// imperfect and a capable viewer can do better.
    /// </summary>
    public void RequestAppearanceRegeneration()
    {
        try { AcroForm.Elements.SetBoolean("/NeedAppearances", true); }
        catch { /* A form that rejects the flag still has its values and its generated appearances. */ }
    }

    /// <summary>Finds a field by fully qualified name.</summary>
    public RawField? Find(string fullyQualifiedName) =>
        Fields.GetValueOrDefault(fullyQualifiedName);

    #endregion
}

#endregion

#region FormWriter — the visitor that writes each field type
// This is where the visitor defined on the model earns its keep. Each field type needs a genuinely
// different write, and the compiler guarantees that adding a new field type cannot be forgotten
// here — which for a save path is worth a great deal, because a silently unhandled field type
// means a value the user entered is quietly dropped.

/// <summary>
/// Writes model field values into raw PDF dictionaries. One instance per save; the target field is
/// set before each visit.
/// </summary>
internal sealed class FormWriter : IFormFieldVisitor<FieldWriteResult>
{
    #region State

    private readonly RawFormAccess _form;
    private RawField _target = null!;

    public FormWriter(RawFormAccess form)
    {
        _form = form;
    }

    /// <summary>
    /// Writes one field's value. Returns a result describing what happened, including any warning
    /// worth telling the user about.
    /// </summary>
    public FieldWriteResult Write(PdfFormField field)
    {
        var raw = _form.Find(field.FullyQualifiedName);

        if (raw is null)
        {
            return FieldWriteResult.NotWritten(
                $"'{field.Label}' could not be found in the file and was not saved.");
        }

        _target = raw;

        try
        {
            // The accessible label is written for every changed field regardless of type, before
            // the type-specific value write. It lives on the field dictionary, not the widget, and
            // it is the whole point of the remediation feature — a label that never reached the
            // file would make the repair theatre.
            if (field.IsLabelModified)
                WriteAccessibleLabel(field);

            return field.IsModified
                ? field.Accept(this)
                : FieldWriteResult.Ok();
        }
        catch (Exception ex)
        {
            return FieldWriteResult.NotWritten($"'{field.Label}' could not be saved: {ex.Message}");
        }
    }

    /// <summary>
    /// Writes the field's tooltip (/TU), which is what a screen reader announces as the field's
    /// name. SetString picks a UTF-16 encoding automatically when the text needs one, so a label in
    /// any language is stored correctly.
    /// </summary>
    private void WriteAccessibleLabel(PdfFormField field)
    {
        if (string.IsNullOrWhiteSpace(field.ToolTip))
            _target.Dictionary.Elements.Remove("/TU");
        else
            _target.Dictionary.Elements.SetString("/TU", field.ToolTip);
    }

    #endregion

    #region Text fields

    public FieldWriteResult VisitText(TextFormField field)
    {
        string value = field.Value;

        if (value.Length == 0)
        {
            _target.Dictionary.Elements.Remove("/V");
            ClearAppearances();
            return FieldWriteResult.Ok();
        }

        // SetString picks a UTF-16 hex encoding automatically when the text needs it, so the stored
        // value is always correct regardless of what the appearance can draw.
        _target.Dictionary.Elements.SetString("/V", value);

        string? warning = null;

        foreach (var widget in _target.Widgets)
            AppearanceStreamBuilder.WriteTextAppearance(_form.Document, widget, value, field.IsMultiline);

        // The stored value is correct either way, but the drawn appearance uses the standard
        // Helvetica font, which cannot show anything outside Latin-1. The user is told, because the
        // consequence lands on whoever opens the form next and they would have no way to know.
        if (!AppearanceStreamBuilder.CanRenderInStandardFont(value))
        {
            warning = $"'{field.Label}' contains characters that cannot be drawn with the standard " +
                      "PDF font. The value is stored correctly, but those characters will show as " +
                      "question marks when the form is viewed.";
        }

        return warning is null ? FieldWriteResult.Ok() : FieldWriteResult.OkWithWarning(warning);
    }

    #endregion

    #region Checkboxes

    public FieldWriteResult VisitCheckBox(CheckBoxFormField field)
    {
        string state = field.IsChecked ? field.CheckedStateName : field.UncheckedStateName;

        // Both /V on the field and /AS on each widget must change. Writing only /V leaves the box
        // looking unticked; writing only /AS leaves the data unchanged. Tools that set just one of
        // them are the reason so many filled forms arrive apparently blank.
        _target.Dictionary.Elements.SetName("/V", state);

        bool everyStateExists = true;

        foreach (var widget in _target.Widgets)
        {
            if (!AppearanceStreamBuilder.SetToggleAppearanceState(widget, state))
                everyStateExists = false;
        }

        if (!everyStateExists && field.IsChecked)
        {
            return FieldWriteResult.OkWithWarning(
                $"'{field.Label}' has been ticked and the value is stored, but this form provides no " +
                "picture for its ticked state, so it may not appear ticked when viewed.");
        }

        return FieldWriteResult.Ok();
    }

    #endregion

    #region Radio groups

    public FieldWriteResult VisitRadioGroup(RadioGroupFormField field)
    {
        string selected = field.SelectedExportValue ?? "Off";

        _target.Dictionary.Elements.SetName("/V", selected);

        // Every button in the group must be told what to show: the chosen one displays its on-state
        // and all the others must be explicitly turned off. Leaving a previously chosen button's
        // /AS alone produces a group that appears to have two answers selected.
        foreach (var widget in _target.Widgets)
        {
            string onState = FindWidgetOnState(widget);

            string state = onState.Equals(selected, StringComparison.Ordinal) ? onState : "Off";
            AppearanceStreamBuilder.SetToggleAppearanceState(widget, state);
        }

        return FieldWriteResult.Ok();
    }

    /// <summary>
    /// Finds a radio button widget's on-state name: the key of its appearance dictionary that is
    /// not /Off. This is what identifies which option a given button represents.
    /// </summary>
    private static string FindWidgetOnState(PdfDictionary widget)
    {
        try
        {
            var normal = widget.Elements.GetDictionary("/AP")?.Elements.GetDictionary("/N");
            if (normal is null)
                return "Off";

            foreach (string key in normal.Elements.Keys)
            {
                string name = key.TrimStart('/');
                if (!name.Equals("Off", StringComparison.Ordinal))
                    return name;
            }
        }
        catch
        {
            // A widget with no appearance dictionary cannot be shown as selected, but the group's
            // value is still written correctly.
        }

        return "Off";
    }

    #endregion

    #region Choice fields

    public FieldWriteResult VisitChoice(ChoiceFormField field)
    {
        if (field.CustomText is { Length: > 0 } typed)
        {
            _target.Dictionary.Elements.SetString("/V", typed);
            _target.Dictionary.Elements.Remove("/I");
            WriteChoiceAppearance(typed);
            return FieldWriteResult.Ok();
        }

        var selected = field.SelectedOptions;

        if (selected.Count == 0)
        {
            _target.Dictionary.Elements.Remove("/V");
            _target.Dictionary.Elements.Remove("/I");
            ClearAppearances();
            return FieldWriteResult.Ok();
        }

        if (selected.Count == 1)
        {
            _target.Dictionary.Elements.SetString("/V", selected[0].ExportValue);
        }
        else
        {
            // Multiple selections are stored as an array of strings.
            var values = new PdfArray(_form.Document);
            foreach (var option in selected)
                values.Elements.Add(new PdfString(option.ExportValue));

            _target.Dictionary.Elements.SetValue("/V", values);
        }

        WriteSelectionIndices(field, selected);

        // The appearance shows the DISPLAY text, not the export value. A country field whose export
        // values are codes must show "Netherlands" on the page, not "NL".
        WriteChoiceAppearance(string.Join(", ", selected.Select(o => o.SpokenText)));

        return FieldWriteResult.Ok();
    }

    /// <summary>
    /// Writes /I, the array of selected option indices. Required for list boxes so the viewer knows
    /// which rows to highlight, and harmless on combo boxes.
    /// </summary>
    private void WriteSelectionIndices(ChoiceFormField field, IReadOnlyList<ChoiceOption> selected)
    {
        try
        {
            var indices = new PdfArray(_form.Document);
            var allOptions = field.Options;

            foreach (var option in selected)
            {
                for (int i = 0; i < allOptions.Count; i++)
                {
                    if (!ReferenceEquals(allOptions[i], option))
                        continue;

                    indices.Elements.Add(new PdfInteger(i));
                    break;
                }
            }

            if (indices.Elements.Count > 0)
                _target.Dictionary.Elements.SetValue("/I", indices);
            else
                _target.Dictionary.Elements.Remove("/I");
        }
        catch
        {
            // The value itself is already written; the index array is an optimisation for viewers.
        }
    }

    private void WriteChoiceAppearance(string text)
    {
        foreach (var widget in _target.Widgets)
            AppearanceStreamBuilder.WriteTextAppearance(_form.Document, widget, text, isMultiline: false);
    }

    #endregion

    #region Buttons and signatures
    // Neither holds a value, so neither is written. They are listed here because the visitor
    // interface requires it, and that requirement is exactly the point: a new field type cannot be
    // added to the model without the compiler forcing a decision about how it is saved.

    public FieldWriteResult VisitPushButton(PushButtonFormField field) =>
        FieldWriteResult.Ok();

    /// <summary>
    /// Writes a placed signature.
    ///
    /// Two routes, and the choice between them is deliberate:
    ///
    ///   FLATTEN (the default) draws the ink into the page itself, tags it as a figure with real
    ///   alternate text, and deletes the signature field. Nothing is left for a viewer to paint
    ///   "click to sign" chrome over, and a screen reader announces our wording rather than an
    ///   empty field. This is the better outcome and it is what happens unless it fails.
    ///
    ///   APPEARANCE STREAM (the fallback) puts the mark in the field's own appearance and leaves
    ///   the field in place. Used only when flattening could not be done, because it is
    ///   non-destructive and always available.
    ///
    /// Neither writes /V. That is where a cryptographic signature would live, and leaving it empty
    /// is what keeps the file honest about which kind of signature it carries.
    /// </summary>
    public FieldWriteResult VisitSignature(SignatureFormField field)
    {
        if (field.PendingMark is not { } mark)
            return FieldWriteResult.Ok();

        if (!mark.IsUsable)
        {
            return FieldWriteResult.NotWritten(
                $"The signature for '{field.Label}' had nothing to draw and was not saved.");
        }

        var widget = _target.SingleWidget ?? _target.Widgets.FirstOrDefault();

        if (widget is null)
        {
            return FieldWriteResult.NotWritten(
                $"'{field.Label}' has nowhere on the page to draw a signature.");
        }

        var flattened = SignatureFlattener.Flatten(_form.Document, _target.Dictionary, widget, mark);

        if (flattened.Succeeded)
            return flattened.Warning is null ? FieldWriteResult.Ok() : FieldWriteResult.OkWithWarning(flattened.Warning);

        // Falling back rather than failing. A signature that is placed but might be covered by a
        // viewer's own chrome is a far better outcome than no signature at all, and the user is
        // told which happened.
        bool wroteAny = false;
        string? appearanceWarning = null;

        foreach (var each in _target.Widgets)
        {
            if (SignatureWriter.WriteInto(_form.Document, each, mark, out string? warning))
                wroteAny = true;

            appearanceWarning ??= warning;
        }

        if (!wroteAny)
        {
            return FieldWriteResult.NotWritten(
                flattened.Warning ?? $"The signature for '{field.Label}' could not be drawn.");
        }

        return FieldWriteResult.OkWithWarning(
            $"The signature was placed, but it could not be flattened into the page " +
            $"({flattened.Warning}). It has been put in the signature field instead, which means " +
            "Adobe Acrobat may draw its own panel over it.");
    }

    #endregion

    #region Helpers

    /// <summary>
    /// Removes generated appearances when a field is cleared, so that an emptied field does not go
    /// on displaying its old value.
    /// </summary>
    private void ClearAppearances()
    {
        foreach (var widget in _target.Widgets)
        {
            try { widget.Elements.Remove("/AP"); }
            catch { /* A widget that keeps a stale picture is a display fault, not a data one. */ }
        }
    }

    #endregion
}

#endregion
